### ISSUE TITLE
WordPress in the browser

### ISSUE THREAD

**Issue by aplamada** [inseri-swiss/inseri-swiss#42]
[WordPress Playground](https://developer.wordpress.org/playground/) can be one way to allow any person to test inseri.
The plugin following could be installed following the documentation - see [Installing plugins](https://wordpress.github.io/wordpress-playground/pages/running-wordpress-in-the-browser.html#installing-plugins).

This is additional to an WP instance that the early adopters can test.

**Comment by aplamada** [comment]
WordPress Playground can be used to install the plugin via the zip archive. 
The admin panel does not work as desired (and therefore the corresponding WebAPI block).
The other blocks look ok.

**Comment by aplamada** [comment]
One can export the content using [Tools -> Export](https://wordpress.org/documentation/article/tools-export-screen/#tools-%e2%86%92-export) and import it in a similar way to the playground. 
The media library content is not really imported (maybe not even exported) but all pages/posts/styles work fine, assuming the same theme. 

For the local Wordpress deployment the experience was good.

**Comment by aplamada** [comment]
https://wasm.wordpress.net/ allows to even download the state and upload it back.  

You can try to upload the next one ... and in the worst example we will ask the users to do this initial manual step. 
[wordpress-playground--wp6.1--php8.0.zip](https://github.com/inseri-swiss/inseri-swiss/files/11100974/wordpress-playground--wp6.1--php8.0.zip)

**Comment by aplamada** [comment]
See https://github.com/WordPress/wordpress-playground/issues/88 for the on-going work.

**Comment by adamziel** [comment]
👋  @aplamada, I just found this issue. You could set up an HTML page that installs and configures the plugin for the user:

```html
<!DOCTYPE html>
<html>
	<head>
		<title>WordPress Playground</title>
	</head>
	<body>
		<iframe id="wp" style="width: 1200px; height: 800px"></iframe>
		<script type="module">
			import { connectPlayground, login, installPlugin } from 'https://unpkg.com/@wp-playground/client/index.js';

			const client = await connectPlayground(
				document.getElementById('wp'),
				{ loadRemote: 'https://playground.wordpress.net/remote.html' }
			);
			
			await client.isReady();
			await login(client, 'admin', 'password');

			// Assuming inseri.zip is hosted with this HTML file:
			const response = await fetch('./inseri.zip');
			const inseriFile = new File([await response.blob()], 'inseri.zip');

			await installPlugin( client, inseriFile );

			// Redirect to the right landing page
			await client.goTo( '/wp-admin/' );
		</script>
	</body>
</html>
```

It might take a while to load so you may want to implement a minimal progress bar to make the wait a better experience. Here's how GlotPress Playground did it: https://github.com/akirk/wp-glotpress-playground/blob/main/index.php

**Comment by aplamada** [comment]
@adamziel Many thanks for the instructions. So far I managed to use the Dockerfile from `compile-wordpress` to create my own local environment. Basically installing the plugin and changing the displayed content. 

```Dockerfile
ADD input /input

RUN cd wordpress && \
  ../wp-cli.phar --allow-root plugin install /input/inseri-core.zip && \
  ../wp-cli.phar --allow-root plugin activate inseri-core

RUN  cd wordpress && \
  ../wp-cli.phar  --allow-root post delete $(../wp-cli.phar --allow-root post list --post_type='page,post' --format=ids) &&\
  ../wp-cli.phar  --allow-root import /input/inseriswiss.WordPress.xml --authors=skip &&\
  ../wp-cli.phar  --allow-root post delete $(../wp-cli.phar --allow-root post list --post_type='page' --format=ids)

```
I still have to learn what to do next.

I was thinking whether it would be possible to use GitHub Pages to host my Playground.  Do you see any limitations?

**Comment by adamziel** [comment]
Oh that Dockerfile [builds a highly optimized `.data` file](https://wordpress.github.io/wordpress-playground/pages/bundling-wordpress-for-the-browser.html) containing WordPress. Surely you can include your plugin in it if you want to shave every microsecond from the initial loading time, but it's pretty inconvenient to work with AND you'll likely need to rebuild it every time a version of WordPress or your plugin is released. 

I'd recommend not starting there.

Instead, you could use the WordPress Playground public API. There's some documentation [here](https://wordpress.github.io/wordpress-playground/pages/embedding-wordpress-playground-on-other-websites.html) and [here](https://wordpress.github.io/wordpress-playground/modules/_wp_playground_client.html) with more to come. In a nutshell, you can embed Playground inside an `<iframe>` and then control it using JavaScript functions - you wouldn't even need to set up Playground locally for that.

However if you'd like to use a local Playground, you'd still use the same public API. The only difference would be the iframe pointing to `http://localhost:4400/remote.html` instead of `https://playground.wordpress.net/remote.html`. Oh, and make sure to run the `npm run dev` command beforehand.

Let me know if that answers some of your questions, I'm happy to keep answering them :-)

**Comment by adamziel** [comment]
> I was thinking whether it would be possible to use GitHub Pages to host my Playground. Do you see any limitations?

I tried that initially! I found that downloading 2MB of data from GitHub pages (`php.wasm`) can be painfully slow. I'm not sure why was that and your experience might be different.

The only real limitation is that Playground uses a network proxy written in PHP. It's only used if you want to install plugins or themes from WordPress.org directory. If you don't need that, then you're good.

**Comment by aplamada** [comment]
Thanks @adamziel ! 
I followed your recommendation and used the public API together with the progress bar - everything is working as desired at least locally using the Live Server from VS Code.

But for my particular use case, it would be convenient to have a way to import some posts from the public WordPress (already exported as a WXR XML file). Do you know how to achieve this?
The aim is to allow the users to see/explore the functionality of the new blocks starting from some examples.

**Comment by adamziel** [comment]
> Thanks @adamziel ! I followed your recommendation and used the public API together with the progress bar - everything is working as desired at least locally using the Live Server from VS Code.

Yay! I'm super glad to hear that

> But for my particular use case, it would be convenient to have a way to import some posts from the public WordPress (already exported as a WXR XML file). Do you know how to achieve this? The aim is to allow the users to see/explore the functionality of the new blocks starting from some examples.

In [a recent PR](https://github.com/WordPress/wordpress-playground/pull/209) I merged [a `submitImporterForm()` helper](https://github.com/WordPress/wordpress-playground/pull/209/files#diff-da53ef93501d6bc36b789bb918e6158cb49aad14cfe26184f24eee80c1c7af9fR111) that does just that! It's not yet released on npm, but you should be able to copy and reuse the code since it's based on the PlaygroundClient object you get from `connectPlayground`.  [source]()

**Comment by aplamada** [comment]
@adamziel Thanks! I start using the Playground Blueprint and it works as desired - so far without importing the WXR but I plan to try it in the near future.
