### ISSUE TITLE
Assess DaSCH for PID integration and long term storage

### ISSUE THREAD

**Issue by aplamada** [inseri-swiss/inseri-swiss#46]
This is a follow up of #7 

We want to evaluate the following dimensions:
- well-established [FAIR](https://www.go-fair.org/fair-principles/) PID solutions (citable is very important) integrated with
- well-established data repository
- with programmatic access
- at a very low cost (ideally free)
- that can guarantee a very good longevity
- interdisciplinary
- and ideally owned by one or several research institutions, and not a commercial one

**Comment by rfbaumgartner** [comment]
FAIR PID:
- DSP gives ARK identifier to web representations of resources. The identifiers are built on the internal IRI that can also be considerent permanent.
- Timestamps can give specific versions for ARK and IRI.

Well-established data repository:
- Backed by SERI

Programmatic access:
- [API documentation](https://docs.dasch.swiss/2023.01.01/DSP-API/01-introduction/what-is-dsp/)

at a very low cost (ideally free):
- Creation of data models and import scripts cost money while other things are usually free.

that can guarantee a very good longevity:
- as every repository DaSCH is dependent on funding and thus political decisions
- DaSCH recommends human-readable files over zipped formats like .zip or .docx due to technical dependencies

interdisciplinary:
- DaSCH focuses on humanities and qualitative data

and ideally owned by one or several research institutions, and not a commercial one:
- non-commercial, recommended by SNSF for data from humanities

**Comment by rfbaumgartner** [comment]
More details about the programmatic access

- DSP allows [representations](https://docs.dasch.swiss/2023.01.01/DSP-API/02-dsp-ontologies/knora-base/#representations) of images, text based documents, binary documents, archives (e.g. zip) and others through specific subclasses. They can be used directly or with an additional subclassing layer that allows more metadata. The subclassing could be done through a shared ontology. Each entry of the type *representation* has exactly one file value.
- On a resource view, reachable by an ARK identifier, a direct link to the file can be copied from the menu of the file viewer. ARK and resource IRIs can be bidirectionally mapped (not sure if permanently) but file download paths are independent. A link to the file can also be taken from the request to get the resource.
- To add files either the DSP admin interface can be used or the API by [first uploading the file to SIPI and then adding the representation](https://docs.dasch.swiss/2023.01.01/DSP-API/03-endpoints/api-v2/editing-values/#creating-file-values).
  - Get token from DSP
  - Upload file via `multipart/form-data` request to SIPI using the token. Save the new file name.
  - Create the resource with additional metadata and the new file name.

**Comment by aplamada** [comment]
Main limitations compared to Zenodo for our use cases:
- domain-specific and this is not going to change
- not intended to just save a ZIP file
- the creation of a project involves a manual step
