### ISSUE TITLE
HTML block

### ISSUE THREAD

**Issue by aplamada** [inseri-swiss/inseri-swiss#51]
Input: HTML as text (content type text/HTML)
Display the content

see https://wordpress.com/support/wordpress-editor/blocks/custom-html-block/ 
Apparently, some HTML tags can have some security implications.

Future idea: 
- input: Style file (CSS): text
- we can imagine generating the XHTML also from XML+XSLT
- markdown can be rendered as well to html
- ...

**Comment by bigaru** [comment]
it's true that some HTML tags can be [dangerous](https://stackoverflow.com/questions/17369559/html-dangerous-tags-to-avoid-while-developing-a-chat-application)
However, a better way to protect a website is, [content-security-policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) 
That's why all tags will be supported

In case of Wordpress.com, it seems like to motivate customer for higher pricing tiers.
